[tool.bumpversion]
current_version = "0.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = true
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "version: {current_version} -> {new_version}"
allow_dirty = false
commit = true
message = "version: {current_version} -> {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "configs/__init__.py"
search = "VERSION = \"{current_version}\""
replace = "VERSION = \"{new_version}\""
